-- Tab
HomeTextTab = "بيت"
MainTextTab = "رئيسي"
ItemTextTab = "غرض"
SeaEventTab = "حدث البحر"
StatsTextTab = "احصائيات"
ShopTextTab = "محل"
IslandTextTab = "جزيرة"
DungeonTextTab = "زنزانة"
CheckerTabText = "فاحص"
PvPTextTab = "حماية الأصناف النباتية"
RaceV4TextTab = "سباق V4"
FruiTextTab = "فاكهة"
ESPTextTab = "إسب"
MiscellaneousTextTab = "متنوع"
VisualTextTab = "مرئي"
SettingsTextTab = "إعدادات"
-- Main
HomeText = "بيت"
-- Config
ConfigText = "التكوين"
WeaponText = "سلاح"
MethodText = "طريقة"
AttackTypeText = "نوع الهجوم"
FastAttackText = "هجوم سريع"
-- Farming
FarmingText = "الزراعة"
AutoFarmLevelText = "مستوى المزرعة الآلية"
AutoFarmNeareastMobsText = "مزرعة السيارات الغوغاء في الشرق الأدنى"
ChestFarmGoodText = "مزرعة الصدر [جيد]"
ChestFarmTweenText = "مزرعة الصدر [توين]"
AutoCastleRaidText = "غارة قلعة السيارات"
-- Farming Mastery
FarmMasteryText = "إتقان الزراعة"
AutoFarmMasteryFruitText = "إتقان الفاكهة في مزرعة السيارات"
AutoFarmMasteryGunText = "إتقان بندقية مزرعة السيارات"
KillAtText = "قتل في (%)"
-- Skill Mastery
SkillMasteryText = "إتقان المهارة"
SkillZText = "المهارة Z"
SkillXText = "المهارة X"
SkillCText = "المهارة C"
SkillVText = "المهارة V"
SkillFText = "المهارة F"
-- Farming Boss
FarmBossText = "رئيس الزراعة"
SelectBossText = "حدد بوس"
AutoFarmBossText = "رئيس مزرعة السيارات"
AutoFarmBossQuestText = "زعيم مزرعة السيارات [المهمة]"
AutoFarmBossAllText = "أوتو فارم بوس [الكل]"
-- Material
MaterialText = "مادة"
SelectMaterialText = "حدد المادة"
AutoFarmMaterialAllText = "مواد مزرعة السيارات"
-- World 1
StatusWorld1Text = "الحالة : العالم 1"
AutoNewWorldText = "عالم السيارات الجديد"
-- World 2
StatusWorld2Text = "الحالة : العالم 2"
AutoNewWorldThirdText = "عالم السيارات الجديد الثالث"
-- Saber World 1
SaberFirstWorldText = "صابر | العالم الأول"
AutoSaberText = "السيارات صابر"
AutoPoleText = "القطب السيارات"
-- Hallow Scythe World 3
HallowSyctheWorldText = "قدس المنجل"
AutoHallowScytheText = "منجل قدس السيارات"
-- Factory World 2
FactorySecondWorldText = "مصنع | عالم ثاني"
AutoFactoryText = "مصنع السيارات"
-- Ectoplasm
EctoplasmText = "الجبلة الخارجية"
AutoEctoplasmText = "الإكتوبلازم التلقائي"
-- Sea Beast World 2
SeaBeastText = "وحش البحر"
AutoSeaBeastKingText = "السيارات وحش البحر الملك"
-- Dack Coat
DarkCoatText = "معطف داكن"
AutoDarkCoatText = "معطف داكن تلقائي"
-- Swan Glasses
SwanGlassesText = "نظارات البجعة"
AutoSwanGlassesText = "نظارات سوان السيارات"
AutoSwanGlassesHopText = "نظارات البجعة التلقائية [القفز]"
-- Sea Rough
SeaRoughText = "البحر هائج"
AutoKillEventText = "القتل التلقائي [الحدث]"
AutoKillTerrorsharkText = "القتل التلقائي لـ Terrorshark"
AutoKillPiranhaText = "قتل تلقائي لسمكة البيرانا"
AutoKillSharkText = "قتل القرش تلقائيًا"
AutoKillFishCrewMemberText = "قتل تلقائي لعضو طاقم السمك"
SetSpeedBoatText = "ضبط القارب السريع"
SpeedBoatText = "قارب سريع"
NoClipRockText = "نوكليب روك"
SelectBringBoatText = "حدد إحضار القارب"
BringBoatText = "إحضار القارب"
-- Rainbow Haki
RainbowHakiText = "قوس قزح هاكي"
AutoRainbowHakiText = "أوتو رينبو هاكي"
AutoRainbowHakiHopText = "هاكي قوس قزح التلقائي [قفزة]"
-- Item
ItemText = "غرض"
AutoEvoRaceV2Text = "سباق السيارات إيفو V2"
AutoBartiloQuestText = "أوتو بارتيلو كويست"
AutoRengokuSwordsText = "سيوف رينجوكو الآلية"
AutoBuyLegendarySwordText = "شراء تلقائي للسيف الأسطوري"
AutoBuyEnchancementText = "تحسين الشراء التلقائي"
AutoMusketeerHatText = "قبعة الفارس التلقائي"
AutoHolyTorchText = "السيارات المقدسة الشعلة"
AutoYamaText = "اوتو ياما"
-- Observation
ObservationText = "ملاحظة"
AutoFarmObservationHakiText = "هاكي مراقبة المزرعة الآلية"
AutoFarmObservationHakiHopText = "هاكي مراقبة المزرعة الآلية [قفزة]"
-- Cursed Dual Katana
CursedDualKatanaText = "كاتانا المزدوجة الملعونة"
AutoCursedDualKatanaText = "كاتانا المزدوجة الملعونة تلقائيًا"
-- Yama Quest
YamaQuestText = "ياما كويست"
AutoYamaQuestOneText = "أوتو ياما كويست [1]"
AutoYamaQuestTwoText = "أوتو ياما كويست [2]"
MobAuraText = "هالة الغوغاء"
-- Rip Indar
RipIndraText = "ريب إندار"
AutoRipIndraBossText = "مزرعة السيارات ريب إندار [الزعيم]"
-- Cake Prince
CakePrinceText = "كعكة الأمير"
AutoFarmCakePrinceText = "أوتو فارم كيك برنس"
AutoSpawnCakePrinceText = "السيارات تفرخ كعكة الأمير"
-- Bone
BoneText = "عظم"
AutoFarmBoneText = "عظم مزرعة السيارات"
AutoRandomBoneText = "العظام العشوائية التلقائية"
-- Elite Hunter
EliteHunterText = "النخبة هنتر"
AutoEliteHunterText = "السيارات النخبة هنتر"
AutoEliteHunterHopText = "صياد النخبة التلقائي [القفز]"
-- Stats
SelectStatsText = "حدد الإحصائيات"
EnableStatsText = "تمكين الإحصائيات"
EnableStatsKaitunText = "احصائيات Eanble كايتون" 
--Shop
SelectShopText = "حدد المتجر"
BuyOnSelectShopText = "شراء على متجر محدد"
-- Island
SelectIslandText = "اختر الجزيرة"
TeleportToFirstWorldText = "النقل الفضائي إلى العالم الأول"
TeleportToSecondWorldText = "النقل الفضائي إلى العالم الثاني"
TeleportToThirdWorldText = "النقل الفضائي إلى العالم الثالث"
TeleportToIslandText = "النقل الفضائي إلى الجزيرة"
StopTeleportText = "إيقاف النقل الفوري"
TeleportToAdvancedFruitDealerText = "النقل الفوري إلى تاجر الفاكهة المتقدم"
TeleportToLegendarySwordDealerText = "النقل الفوري إلى تاجر السيف الأسطوري"
TeleportToMasterofEnhancementText = "النقل الفضائي إلى ماجستير في التعزيز"
-- Mirage Island
MirageIslandText = "جزيرة ميراج"
AutoTeleportToMirageIsland = "النقل الفضائي التلقائي إلى جزيرة ميراج"
TeleportToGearText = "النقل الفضائي إلى العتاد"
TeleportToGearBlueText = "النقل الفضائي إلى جير بلو"
-- Kitsune Island
KitsuneIslandText = "جزيرة كيتسون"
AutoTeleportToKitsuneIslandText = "النقل الفوري التلقائي إلى جزيرة كيتسون"
AutoTeleportToKitsuneShrineText = "النقل الفوري التلقائي إلى ضريح كيتسوني"
AutoCollectAzureEmberText = "التجميع التلقائي لـ Azure Ember"
-- Raid
SelectChipsText = "حدد الرقائق"
AutoBuyChipsText = "شراء رقائق السيارات"
AutoStartRaidText = "بدء الغارة تلقائيًا"
KillAuraText = "أقتل اورا"
AutoNextIslandText = "جزيرة السيارات التالية"
AutoAwakenedText = "الاستيقاظ التلقائي"
-- Law Raid Second World
LawRaidText = "غارة القانون"
AutoBuyLawChipText = "شراء السيارات رقاقة القانون"
AutoStartLawRaidText = "البدء التلقائي في غارة القانون"
AutoKillLawText = "قانون القتل التلقائي"
-- PvP
SelectPlayerText = "حدد لاعب"
AimBotSkillText = "مهارة ايمبوت"
AimBotGunText = "بندقية ايمبوت"
TeleportToPlayerText = "النقل الفوري للاعب"
SpectatedPlayerText = "لاعب متفرج"
AutoKillPlayerText = "لاعب القتل التلقائي"
EnablePvPText = "تمكين حماية الأصناف النباتية"
SafeModeText = "الوضع الآمن"
RespawnText = "إعادة الظهور"
-- Race V4

LockMoonText = "قفل القمر"
TeleportToTopGreatTreeText = "النقل الفوري إلى أعلى الشجرة العظيمة"
TeleportToTimpleOfTimeText = "النقل الفضائي إلى تيمبل من الزمن"
TeleportToLeverPullText = "النقل الفضائي إلى رافعة السحب"
TeleportToAcientOneText = "النقل الفضائي إلى Acient One"
UnlockLeverText = "فتح الرافعة"
TeleportCyborgDoorText = "النقل الفضائي سايبورغ الباب"
TeleportFishDoorText = "باب الأسماك النقل الفضائي"
TeleportGhoulDoorText = "باب الغول النقل الفضائي"
TeleportHumanDoorText = "النقل الفضائي باب الإنسان"
TeleportMinkDoorText = "باب المنك النقل الفضائي"
TeleportToSkyDoorText = "باب السماء الفضائي"
CompleteAngelTrialText = "استكمال محاكمة الملاك"
CompleteRabbitTrialText = "محاكمة الأرنب كاملة"
CompleteCyborgTrialText = "أكمل تجربة سايبورغ"
TeleportPVPZoneText = "منطقة النقل الفضائي PVP"
TeleportToSafeZonePVPText = "النقل الفوري إلى المنطقة الآمنة PVP"
-- Sniper Fruit
SelectFruitSniperText = "حدد قناص الفاكهة"
AutoBuyFruitSniperText = "شراء السيارات قناص الفاكهة"
-- Fruit
FruitText = "فاكهة"
SelectFruitText = "حدد الفاكهة"
AutoEatFruitText = "أكل الفاكهة تلقائيًا"
GetFruitInventoryText = "الحصول على جرد الفاكهة"
AutoRandomFruitText = "فاكهة عشوائية تلقائية"
AutoStoreFruitText = "متجر السيارات الفاكهة"
-- ESP
ESPPlayerText = "لاعب إسب"
ESPChestText = "صندوق ESP"
ESPDevilFruitText = "ESP فاكهة الشيطان"
ESPFlowerText = "زهرة إسب"
ESPIslandText = "جزيرة إي إس بي"
--Miscellaneous Server
HopServerText = "خادم هوب"
HopLowPlayerServerText = "قفز خادم لاعب منخفض"
RejoinServerText = "إعادة الانضمام إلى الخادم"
--Miscellaneous Team
MiscellaneousTeamText = "فريق متنوع"
JoinPiratesTeamText = "انضم إلى فريق القراصنة"
JoinMarinesTeamText = "انضم إلى فريق مشاة البحرية"
--Miscellaneous 
MiscellaneousText = "متنوع"
RedeemCodeAllText = "استرداد الرمز [الكل]"
DevilShopText = "متجر الشيطان"
ColorHakiText = "اللون هاكي"
TitleNameText = "اسم العنوان"
AwakeningText = "الصحوة"
RemoveFogText = "إزالة الضباب"
ClockTimeDayText = "يوم الساعة"
WalkOnWaterText = "المشي على الماء"
infinityAbilityText = "القدرة اللانهائية"
NoDashCooldownText = "لا يوجد داش كولداون"
InfinitiesGeppoText = "اللانهاية جيبو"
InfinitiesEnergyText = "إنفينيتي إنيرجي"
-- Rain Fruit
RainFruitText = "فاكهة المطر"
InstantLevelBeliEXPText = "المستوى الفوري/بيلي/EXP"
LevelText = "مستوى"
EXPText = "خبرة"
BeliText = "بيلي"
FragmentsText = "فتات"
HealthText = "صحة"
EnergyText = "طاقة"
-- Settings
BypassAntiCheatText = "تجاوز مكافحة الغش: مكافحة العلم"
AutoHakiText = "أوتو هاكي"
AutoKenText = "أوتو كين"
BringMobText = "إحضار الغوغاء"
RemoveDamageText = "إزالة النص الضرر"
RemoveNotifyText = "إزالة الإخطار"
WhiteScreenText = "شاشة بيضاء"
