-- Main
HomeText = "Home"
-- Config
ConfigText = "Config"
WeaponText = "Weapon"
MethodText = "Method"
AttackTypeText = "Attack Type"
FastAttackText = "Fast Attack"
-- Farming
FarmingText = "Farming"
AutoFarmLevelText = "Auto Farm Level"
AutoFarmNeareastMobsText = "Auto Farm Neareast Mobs"
ChestFarmGoodText = "Chest Farm [Good]"
ChestFarmTweenText = "Chest Farm [Tween]"
AutoCastleRaidText = "Auto Castle Raid"
-- Farming Mastery
FarmMasteryText = "Farming Mastery"
AutoFarmMasteryFruitText = "Auto Farm Fruit Mastery"
AutoFarmMasteryGunText = "Auto Farm Gun Mastery"
KillAtText = "Kill At (%)"
-- Skill Mastery
SkillMasteryText = "Skill Mastery"
SkillZText = "Skill Z"
SkillXText = "Skill X"
SkillCText = "Skill C"
SkillVText = "Skill V"
SkillFText = "Skill F"
-- Farming Boss
FarmBossText = "Farming Boss"
SelectBossText = "Select Boss"
AutoFarmBossText = "Auto Farm Boss"
AutoFarmBossQuestText = "Auto Farm Boss [Quest]"
AutoFarmBossAllText = "Auto Farm Boss [All]"
-- Material
MaterialText = "Material"
SelectMaterialText = "Select Material"
AutoFarmMaterialAllText = "Auto Farm Material"
-- World 1
StatusWorld1Text = "Status : World 1"
AutoNewWorldText = "Auto New World"
-- World 2
StatusWorld2Text = "Status : World 2"
AutoNewWorldThirdText = "Auto New World Third"
-- Saber World 1
SaberFirstWorldText = "Saber | First World"
AutoSaberText = "Auto Saber"
AutoPoleText = "Auto Saber"
-- Hallow Scythe World 3
HallowSyctheWorldText = "Hallow Scythe"
AutoHallowScytheText = "Auto Hallow Scythe"
-- Factory World 2
FactorySecondWorldText = "Factory | Second World"
AutoFactoryText = "Auto Factory"
-- Ectoplasm
EctoplasmText = "Ectoplasm"
AutoFactoryText = "Auto Ectoplasm"
-- Sea Beast World 2
SeaBeastText = "Sea Beast"
AutoSeaBeastKingText = "Auto Sea Beast King"
-- Dack Coat
DarkCoatText = "Dark Coat"
AutoDarkCoatText = "Auto Dark Coat"
-- Swan Glasses
SwanGlassesText = "Swan Glasses"
AutoSwanGlassesText = "Auto Swan Glasses"
AutoSwanGlassesHopText = "Auto Swan Glasses [Hop]"
-- Sea Rough
SeaRoughText = "Sea Rough"
AutoKillEventText = "Auto Kill [Event]"
AutoKillTerrorsharkText = "Auto Kill Terrorshark"
AutoKillPiranhaText = "Auto Kill Piranha"
AutoKillSharkText = "Auto Kill Shark"
AutoKillFishCrewMemberText = "Auto Kill Fish Crew Member"
SetSpeedBoatText = "Set Speed boat"
SpeedBoatText = "Speed Boat"
NoClipRockText = "Noclip Rock"
-- Rainbow Haki
RainbowHakiText = "Rainbow Haki"
AutoRainbowHakiText = "Auto Rainbow Haki"
AutoRainbowHakiHopText = "Auto Rainbow Haki [Hop]"
-- Item
ItemText = "Item"
AutoEvoRaceV2Text = "Auto Evo Race V2"
AutoBartiloQuestText = "Auto Bartilo Quest"
AutoRengokuSwordsText = "Auto Rengoku Swords"
AutoBuyLegendarySwordText = "Auto Buy Legendary Sword"
AutoBuyEnchancementText = "Auto Buy Enchancement"
AutoMusketeerHatText = "Auto Musketeer Hat"
AutoHolyTorchText = "Auto Holy Torch"
AutoYamaText = "Auto Yama"
-- Observation
ObservationText = "Observation"
AutoFarmObservationHakiText = "Auto Farm Observation Haki"
AutoFarmObservationHakiHopText = "Auto Farm Observation Haki [Hop]"
-- Rip Indar
RipIndraText = "Rip Indar"
AutoRipIndraBossText = "Auto Farm Rip Indar [Boss]"
-- Cake Prince
CakePrinceText = "Cake Prince"
AutoFarmCakePrinceText = "Auto Farm Cake Prince"
AutoSpawnCakePrinceText = "Auto Spawn Cake Prince"
-- Bone
BoneText = "Bone"
AutoFarmBone = "Auto Farm Bone"
AutoRandomBone = "Auto Random Bone"
-- Elite Hunter
EliteHunterText = "Elite Hunter"
AutoEliteHunterText = "Auto Elite Hunter"
AutoEliteHunterHopText = "Auto Elite Hunter [Hop]"
-- Stats
SelectStatsText = "Select Stats"
EnableStatsText = "Eanble Stats"
EnableStatsKaitunText = "Eanble Stats Kaitun" 
--Shop
SelectShopText = "Select Shop"
BuyOnSelectShopText = "Buy On Select Shop"
-- Island
SelectIslandText = "Select Island"
TeleportToFirstWorldText = "Teleport To First World"
TeleportToSecondWorldText = "Teleport To Second World"
TeleportToThirdWorldText = "Teleport To Third World"
TeleportToIslandText = "Teleport To Island"
StopTeleportText = "Stop Teleport"
TeleportToAdvancedFruitDealerText = "Teleport To Advanced Fruit Dealer"
TeleportToLegendarySwordDealerText = "Teleport To Legendary Sword Dealer"
TeleportToMasterofEnhancementText = "Teleport To Master of Enhancement"
-- Mirage Island
MirageIslandText = "Mirage Island"
AutoTeleportToMirageIsland = "Auto Teleport To Mirage Island"
TeleportToGearText = "Teleport To Gear"
TeleportToGearBlueText = "Teleport To Gear Blue"
-- Kitsune Island
KitsuneIslandText = "Kistune Island"
AutoTeleportToKitsuneIslandText = "Auto Teleports To Kitsune Island"
AutoTeleportToKitsuneShrineText = "Auto Teleports To Kitsune Shrine"
AutoCollectAzureEmberText = "Auto Collect Azure Ember"
-- Raid
SelectChipsText = "Select Chips"
AutoBuyChipsText = "Auto Buy Chips"
AutoStartRaidText = "Auto Start Raid"
KillAuraText = "Kill Aura"
AutoNextIslandText = "Auto Next Island"
AutoAwakenedText = "Auto Awakened"
-- Law Raid Second World
LawRaidText = "Law Raid"
AutoBuyLawChipText = "Auto Buy Law Chip"
AutoStartLawRaidText = "Auto Start Law Raid"
AutoKillLawText = "Auto Kill Law"
-- PvP
SelectPlayerText = "Select Player"
AimBotSkillText = "Aimbot Skill"
AimBotGunText = "Aimbot Gun"
TeleportToPlayerText = "Teleport To Player"
SpectatedPlayerText = "Spectated Player"
AutoKillPlayerText = "Auto Kill Player"
EnablePvPText = "Enabled PvP"
SafeModeText = "Safe Mode"
RespawnText = "Respawn"
-- Race V4

LockMoonText = "Lock Moon"
TeleportToTopGreatTreeText = "Teleport To Top Great Tree"
TeleportToTimpleOfTimeText = "Teleport To Timple Of Time"
TeleportToLeverPullText = "Teleport To Lever Pull"
TeleportToAcientOneText = "Teleport To Acient One"
UnlockLeverText = "Unlock Lever"
TeleportCyborgDoorText = "Teleport Cyborg Door"
TeleportFishDoorText = "Teleport Fish Door"
TeleportGhoulDoorText = "Teleport Ghoul Door"
TeleportHumanDoorText = "Teleport Human Door"
TeleportMinkDoorText = "Teleport Mink Door"
TeleportToSkyDoorText = "Teleport Sky Door"
CompleteAngelTrialText = "Complete Angel Trial"
CompleteRabbitTrialText = "Complete Rabbit Trial"
CompleteCyborgTrialText = "Complete Cyborg Trial"
TeleportPVPZoneText = "Teleport PVP Zone"
TeleportToSafeZonePVPText = "Teleport To Safe Zone PVP"
-- Sniper Fruit
SelectFruitSniperText = "Select Fruit Sniper"
AutoBuyFruitSniperText = "Auto Buy Fruit Sniper"
-- Fruit
FruitText = "Fruit"
SelectFruitText = "Select Fruit"
AutoEatFruitText = "Auto Eat Fruit"
GetFruitInventoryText = "Get Fruit Inventory"
AutoRandomFruitText = "Auto Random Fruit"
AutoStoreFruitText = "Auto Store Fruit"
-- ESP
ESPPlayerText = "ESP Player"
ESPChestText = "ESP Chest"
ESPDevilFruitText = "ESP Devil Fruit"
ESPFlowerText = "ESP Flower"
ESPIslandText = "ESP Island"
--Miscellaneous Server
HopServerText = "Hop Server"
HopLowPlayerServerText = "Hop Low Player Server"
RejoinServerText = "Rejoin Server"
--Miscellaneous Team
MiscellaneousTeamText = "Miscellaneous Team"
JoinPiratesTeamText = "Join Pirates Team"
JoinMarinesTeamText = "Join Marines Team"
--Miscellaneous 
MiscellaneousText = "Miscellaneous"
RedeemCodeAllText = "Redeem Code [All]"
DevilShopText = "Devil Shop"
ColorHakiText = "Color Haki"
TitleNameText = "Title Name"
AwakeningText = "Awakening"
RemoveFogText = "Remove Fog"
ClockTimeDayText = "ClockTime Day"
WalkOnWaterText = "Walk On Water"
infinityAbilityText = "infinity Ability"
NoDashCooldownText = "No Dash Cooldown"
InfinitiesGeppoText = "Infinities Geppo"
InfinitiesEnergyText = "Infinities Energy"
-- Rain Fruit
RainFruitText = "Rain Fruit"
InstantLevelBeliEXPText = "Instant Level/Beli/EXP"
LevelText = "Level"
EXPText = "EXP"
BeliText = "Beli"
FragmentsText = "Fragments"
HealthText = "Health"
EnergyText = "Energy"
-- Settings
BypassAntiCheatText = "Bypass Anti-Cheat: Anti Flag"
AutoHakiText = "Auto Haki"
AutoKenText = "Auto Ken"
BringMobText = "Bring Mob"
RemoveDamageText = "Remove Damage Text"
RemoveNotifyText = "Remove Notify"
WhiteScreenText = "White Screen"
