-- Tab
HomeTextTab = "Lar"
MainTextTab = "Principal"
ItemTextTab = "Item"
SeaEventTab = "Evento Marítimo"
StatsTextTab = "Estatísticas"
ShopTextTab = "Comprar"
IslandTextTab = "Ilha"
DungeonTextTab = "Masmorra"
PvPTextTab = "JxJ"
CheckerTabText = "Verificador"
RaceV4TextTab = "Corrida V4"
FruiTextTab = "Fruta"
ESPTextTab = "PES"
MiscellaneousTextTab = "Diversas"
VisualTextTab = "Visual"
SettingsTextTab = "Configurações"
-- Main
HomeText = "Lar"
-- Config
ConfigText = "Configuração"
WeaponText = "Arma"
MethodText = "Método"
AttackTypeText = "Tipo de ataque"
FastAttackText = "Ataque Rápido"
-- Farming
FarmingText = "Agricultura"
AutoFarmLevelText = "Nível de fazenda automática"
AutoFarmFastSkipText = "Salto rápido automático nível 1-300"
AutoFarmNeareastMobsText = "Auto Farm Mobs Próximos"
ChestFarmGoodText = "Fazenda de Peito [Bom]"
ChestFarmTweenText = "Fazenda de Peito [Tween]"
AutoCastleRaidText = "Ataque Automático ao Castelo"
-- Farming Mastery
FarmMasteryText = "Maestria Agrícola"
AutoFarmMasteryFruitText = "Domínio de frutas na fazenda automática"
AutoFarmMasteryGunText = "Maestria em armas de fazenda automática"
KillAtText = "Matar em (%)"
-- Skill Mastery
SkillMasteryText = "Domínio de habilidades"
SkillZText = "Habilidade Z"
SkillXText = "Habilidade X"
SkillCText = "Habilidade C"
SkillVText = "Habilidade V"
SkillFText = "Habilidade F"
-- Farming Boss
FarmBossText = "Chefe agrícola"
SelectBossText = "Selecione Chefe"
AutoFarmBossText = "Chefe da Fazenda Automóvel"
AutoFarmBossQuestText = "Chefe da Fazenda Automática [Missão]"
AutoFarmBossAllText = "Chefe da Fazenda Automóvel [Todos]"
-- Material
MaterialText = "Material"
SelectMaterialText = "Selecione o Material"
AutoFarmMaterialAllText = "Material para fazenda automotiva"
-- World 1
StatusWorld1Text = "Situação: Mundo 1"
AutoNewWorldText = "Auto Novo Mundo"
-- World 2
StatusWorld2Text = "Situação: Mundo 2"
AutoNewWorldThirdText = "Auto Novo Mundo Terceiro"
-- Saber World 1
SaberFirstWorldText = "Sabre | Primeiro mundo"
AutoSaberText = "Sabre Automático"
AutoPoleText = "Pólo Automático"
-- Hallow Scythe World 3
HallowSyctheWorldText = "Foice Sagrada"
AutoHallowScytheText = "Foice Sagrada Automática"
-- Factory World 2
FactorySecondWorldText = "Fábrica | Segundo Mundo"
AutoFactoryText = "Fábrica de automóveis"
-- Ectoplasm
EctoplasmText = "Ectoplasma"
AutoEctoplasmText = "Ectoplasma Automático"
-- Sea Beast World 2
SeaBeastText = "Sea Beast"
AutoSeaBeastKingText = "Auto Sea Beast King"
-- Dack Coat
DarkCoatText = "Casaco Escuro"
AutoDarkCoatText = "Casaco Escuro Automático"
-- Swan Glasses
SwanGlassesText = "Óculos de cisne"
AutoSwanGlassesText = "Óculos de Cisne Automático"
AutoSwanGlassesHopText = "Óculos Auto Swan [Hop]"
-- Sea Rough
SeaRoughText = "Mar agitado"
AutoSailBoatText = "Barco à vela automático"
AutoPressWText = "Pressione automaticamente W"
AutoFindLeviathanText = "Localização automática do Leviatã"
AutoKillEventText = "Morte Automática [Evento]"
AutoKillGhostShipText = "Navio fantasma de morte automática"
AutoKillShipText = "Navio de destruição automática"
AutoKillTerrorsharkText = "Morte automática Terrorshark"
AutoKillPiranhaText = "Piranha de matar automaticamente"
AutoKillSharkText = "Auto matar tubarão"
AutoKillFishCrewMemberText = "Membro da tripulação do Auto Kill Fish"
SetSpeedBoatText = "Definir lancha"
SpeedBoatText = "Lancha"
NoClipRockText = "Noclip Rock"
SelectBringBoatText = "Selecione Trazer Barco"
BringBoatText = "Traga Barco"
-- Rainbow Haki
RainbowHakiText = "Haki arco-íris"
AutoRainbowHakiText = "Auto arco-íris Haki"
AutoRainbowHakiHopText = "Auto Rainbow Haki [Hop]"
-- Item
ItemText = "Item"
AutoEvoRaceV2Text = "Auto Evo Race V2"
AutoBartiloQuestText = "Auto Bartilo Quest"
AutoRengokuSwordsText = "Espadas Auto Rengoku"
AutoBuyLegendarySwordText = "Espada lendária para compra automática"
AutoBuyEnchancementText = "Aprimoramento de compra automática"
AutoMusketeerHatText = "Chapéu de mosqueteiro automático"
AutoHolyTorchText = "Tocha Sagrada Automática"
AutoYamaText = "Auto Yama"
-- Observation
ObservationText = "Observação"
AutoFarmObservationHakiText = "Observação da Fazenda Automóvel Haki"
AutoFarmObservationHakiHopText = "Observação da Fazenda Automática Haki [Hop]"
-- Cursed Dual Katana
CursedDualKatanaText = "Katana Dupla Amaldiçoada"
AutoCursedDualKatanaText = "Katana Dupla Amaldiçoada Automática"
-- Yama Quest
YamaQuestText = "Missão Yama"
AutoYamaQuestOneText = "Auto Yama Quest [1]"
AutoYamaQuestTwoText = "Auto Yama Quest [2]"
MobAuraText = "Aura da Máfia"
-- Rip Indar
RipIndraText = "Rip Indar"
AutoRipIndraBossText = "Auto Farm Rip Indar [Chefe]"
-- Cake Prince
CakePrinceText = "Bolo Príncipe"
AutoFarmCakePrinceText = "Auto Fazenda Bolo Príncipe"
AutoSpawnCakePrinceText = "Príncipe do Bolo de Spawn Automático"
-- Bone
BoneText = "Osso"
AutoFarmBoneText = "Osso da Fazenda Automática"
AutoRandomBoneText = "Osso Aleatório Automático"
-- Elite Hunter
EliteHunterText = "Caçador de elite"
AutoEliteHunterText = "Caçador de Elite Automóvel"
AutoEliteHunterHopText = "Caçador de Elite Automático [Salto]"
-- Stats
SelectStatsText = "Selecione estatísticas"
EnableStatsText = "Ativar estatísticas"
EnableStatsKaitunText = "Estatísticas de Eanble Kaitun" 
--Shop
SelectShopText = "Selecione Loja"
BuyOnSelectShopText = "Compre na loja selecionada"
-- Island
SelectIslandText = "Selecione Ilha"
TeleportToFirstWorldText = "Teleporte para o primeiro mundo"
TeleportToSecondWorldText = "Teleporte para o segundo mundo"
TeleportToThirdWorldText = "Teleporte para o Terceiro Mundo"
TeleportToIslandText = "Teleporte para a ilha"
StopTeleportText = "Pare o teletransporte"
TeleportToAdvancedFruitDealerText = "Teletransporte-se para o revendedor avançado de frutas"
TeleportToLegendarySwordDealerText = "Teletransporte-se para o lendário negociante de espadas"
TeleportToMasterofEnhancementText = "Teletransporte para o Mestre do Aprimoramento"
-- Mirage Island
MirageIslandText = "Ilha Miragem"
AutoTeleportToMirageIsland = "Teletransporte automático para a Ilha Mirage"
TeleportToGearText = "Teleporte para equipamento"
TeleportToGearBlueText = "Teleporte para engrenagem azul"
-- Kitsune Island
KitsuneIslandText = "Ilha Kitsune"
AutoTeleportToKitsuneIslandText = "Auto teletransporta para a Ilha Kitsune"
AutoTeleportToKitsuneShrineText = "Auto teletransporta para o Santuário Kitsune"
AutoCollectAzureEmberText = "Coleta automática de Azure Ember"
-- Raid
SelectChipsText = "Selecione Fichas"
AutoBuyChipsText = "Fichas de compra automática"
AutoStartRaidText = "Início automático do ataque"
KillAuraText = "Aura mortal"
AutoNextIslandText = "Auto Próxima Ilha"
AutoAwakenedText = "Auto despertado"
-- Law Raid Second World
LawRaidText = "Ataque à lei"
AutoBuyLawChipText = "Chip de lei de compra de automóveis"
AutoStartLawRaidText = "Início automático do ataque à lei"
AutoKillLawText = "Lei de morte automática"
-- PvP
SelectPlayerText = "Selecione o jogador"
AimBotSkillText = "Habilidade de Aimbot"
AimBotGunText = "Arma Aimbot"
TeleportToPlayerText = "Teleporte para o jogador"
SpectatedPlayerText = "Jogador Espectado"
AutoKillPlayerText = "Matar automaticamente o jogador"
EnablePvPText = "PvP habilitado"
SafeModeText = "Modo de segurança"
RespawnText = "reaparecimento"
-- Race V4

LockMoonText = "Bloquear Lua"
TeleportToTopGreatTreeText = "Teleporte para o topo da grande árvore"
TeleportToTimpleOfTimeText = "Teleporte para Timple Of Time"
TeleportToLeverPullText = "Teleporte para puxar a alavanca"
TeleportToAcientOneText = "Teleporte para o Ancião"
UnlockLeverText = "Alavanca de desbloqueio"
TeleportCyborgDoorText = "Porta Ciborgue de Teletransporte"
TeleportFishDoorText = "Porta de teletransporte para peixes"
TeleportGhoulDoorText = "Porta Ghoul de Teletransporte"
TeleportHumanDoorText = "Porta humana de teletransporte"
TeleportMinkDoorText = "Porta de vison de teletransporte"
TeleportToSkyDoorText = "Porta do céu de teletransporte"
CompleteAngelTrialText = "Conclua o Teste do Anjo"
CompleteRabbitTrialText = "Teste completo do coelho"
CompleteCyborgTrialText = "Teste completo do Cyborg"
TeleportPVPZoneText = "Zona PVP de teletransporte"
TeleportToSafeZonePVPText = "Teleporte para zona segura PVP"
-- Sniper Fruit
SelectFruitSniperText = "Selecione o atirador de frutas"
AutoBuyFruitSniperText = "Atirador de frutas para compra automática"
-- Fruit
FruitText = "Fruta"
SelectFruitText = "Selecione Fruta"
AutoEatFruitText = "Comer frutas automaticamente"
GetFruitInventoryText = "Obtenha o inventário de frutas"
AutoRandomFruitText = "Fruta Aleatória Automática"
AutoStoreFruitText = "Frutas para loja de automóveis"
-- ESP
ESPPlayerText = "Jogador ESP"
ESPChestText = "Baú ESP"
ESPDevilFruitText = "Fruta do Diabo ESP"
ESPFlowerText = "Flor ESP"
ESPIslandText = "Ilha ESP"
ESPMirageText = "ESP Ilha Miragem"
--Miscellaneous Server
HopServerText = "Servidor de salto"
HopLowPlayerServerText = "Servidor de jogador com salto baixo"
RejoinServerText = "Reingressar no servidor"
--Miscellaneous Team
MiscellaneousTeamText = "Equipe Diversos"
JoinPiratesTeamText = "Junte-se à equipe dos piratas"
JoinMarinesTeamText = "Junte-se à equipe de fuzileiros navais"
--Miscellaneous 
MiscellaneousText = "Diversas"
RedeemCodeAllText = "Resgatar código [todos]"
DevilShopText = "Loja do Diabo"
ColorHakiText = "Cor Haki"
TitleNameText = "Nome do título"
AwakeningText = "Despertar"
RemoveFogText = "Remover nevoeiro"
ClockTimeDayText = "Hora do Relógio Dia"
WalkOnWaterText = "Andar na água"
infinityAbilityText = "Habilidade infinita"
NoDashCooldownText = "Sem resfriamento do Dash"
InfinitiesGeppoText = "Geppo do Infinito"
InfinitiesEnergyText = "Energia Infinita"
-- Rain Fruit
RainFruitText = "Fruta da Chuva"
InstantLevelBeliEXPText = "Nível Instantâneo/Beli/EXP"
LevelText = "Nível"
EXPText = "EXP"
BeliText = "Beli"
FragmentsText = "Fragmentos"
HealthText = "Saúde"
EnergyText = "Energia"
-- Settings
BypassAntiCheatText = "Ignorar Anti-Cheat: Anti Flag"
AutoHakiText = "Haki automático"
AutoKenText = "Auto Ken"
BringMobText = "Traga multidão"
RemoveDamageText = "Remover texto de dano"
RemoveNotifyText = "Remover notificação"
WhiteScreenText = "Tela branca"
