-- Tab
HomeTextTab = "บ้าน"
MainTextTab = "หลัก"
ItemTextTab = "รายการ"
SeaEventTab = "งานทะเล"
StatsTextTab = "สถิติ"
ShopTextTab = "ร้านค้า"
IslandTextTab = "เกาะ"
DungeonTextTab = "ดันเจี้ยน"
PvPTextTab = "พีวีพี"
RaceV4TextTab = "เรซ V4"
FruiTextTab = "ผลไม้"
ESPTextTab = "อีพีเอส"
CheckerTabText = "ตัวตรวจสอบ"
MiscellaneousTextTab = "เบ็ดเตล็ด"
VisualTextTab = "ภาพ"
SettingsTextTab = "การตั้งค่า"
-- Main
HomeText = "บ้าน"
-- Config
ConfigText = "การกำหนดค่า"
WeaponText = "อาวุธ"
MethodText = "วิธี"
AttackTypeText = "ประเภทการโจมตี"
FastAttackText = "โจมตีเร็ว"
-- Farming
FarmingText = "การทำฟาร์ม"
AutoFarmLevelText = "ระดับฟาร์มอัตโนมัติ"
AutoFarmFastSkipText = "ข้ามอัตโนมัติอย่างรวดเร็วระดับ 1-300"
AutoFarmNeareastMobsText = "ฟาร์มอัตโนมัติ Mobs ที่ใกล้ที่สุด"
ChestFarmGoodText = "ฟาร์มหน้าอก [ดี]"
ChestFarmTweenText = "ฟาร์มหน้าอก [Tween]"
AutoCastleRaidText = "การโจมตีปราสาทอัตโนมัติ"
-- Farming Mastery
FarmMasteryText = "ความเชี่ยวชาญด้านการเกษตร"
AutoFarmMasteryFruitText = "การเรียนรู้ผลไม้ฟาร์มอัตโนมัติ"
AutoFarmMasteryGunText = "ความเชี่ยวชาญปืนฟาร์มอัตโนมัติ"
KillAtText = "ฆ่าที่ (%)"
-- Skill Mastery
SkillMasteryText = "ความเชี่ยวชาญด้านทักษะ"
SkillZText = "ทักษะ Z"
SkillXText = "ทักษะ X"
SkillCText = "ทักษะ C"
SkillVText = "ทักษะ V"
SkillFText = "ทักษะ F"
-- Farming Boss
FarmBossText = "หัวหน้าฝ่ายเกษตรกรรม"
SelectBossText = "เลือกบอส"
AutoFarmBossText = "บอสฟาร์มอัตโนมัติ"
AutoFarmBossQuestText = "บอสฟาร์มอัตโนมัติ [Quest]"
AutoFarmBossAllText = "บอสฟาร์มอัตโนมัติ [ทั้งหมด]"
-- Material
MaterialText = "วัสดุ"
SelectMaterialText = "เลือกวัสดุ"
AutoFarmMaterialAllText = "วัสดุฟาร์มอัตโนมัติ"
-- World 1
StatusWorld1Text = "สถานะ : โลก 1"
AutoNewWorldText = "ออโต้นิวเวิลด์"
-- World 2
StatusWorld2Text = "สถานะ : โลก 2"
AutoNewWorldThirdText = "ออโต้นิวเวิลด์ที่สาม"
-- Saber World 1
SaberFirstWorldText = "เซเบอร์ | โลกที่หนึ่ง"
AutoSaberText = "ออโต้เซเบอร์"
AutoPoleText = "เสาออโต้"
-- Hallow Scythe World 3
HallowSyctheWorldText = "ฮอลโลว์เคียว"
AutoHallowScytheText = "เคียวฮอลโลว์อัตโนมัติ"
-- Factory World 2
FactorySecondWorldText = "โรงงาน | โลกที่สอง"
AutoFactoryText = "โรงงานรถยนต์"
-- Ectoplasm
EctoplasmText = "เอ็กโตพลาสซึม"
AutoEctoplasmText = "ออโต้พลาสซึม"
-- Sea Beast World 2
SeaBeastText = "สัตว์ทะเล"
AutoSeaBeastKingText = "ออโต้ ราชาสัตว์ทะเล"
-- Dack Coat
DarkCoatText = "เสื้อคลุมสีเข้ม"
AutoDarkCoatText = "เคลือบสีเข้มอัตโนมัติ"
-- Swan Glasses
SwanGlassesText = "หงส์แก้ว"
AutoSwanGlassesText = "แว่นออโต้หงส์"
AutoSwanGlassesHopText = "แว่นตาออโต้หงส์ [Hop]"
-- Sea Rough
SeaRoughText = "ทะเลหยาบ"
AutoSailBoatText = "เรือใบอัตโนมัติ"
AutoPressWText = "กดอัตโนมัติ W"
AutoFindLeviathanText = "ค้นหาเลวีอาธานอัตโนมัติ"
AutoKillEventText = "ฆ่าอัตโนมัติ [กิจกรรม]"
AutoKillGhostShipText = "ฆ่าเรือผีโดยอัตโนมัติ"
AutoKillShipText = "เรือฆ่าอัตโนมัติ"
AutoKillTerrorsharkText = "ฆ่า Terrorshark อัตโนมัติ"
AutoKillPiranhaText = "ฆ่าปิรันย่าอัตโนมัติ"
AutoKillSharkText = "ฆ่าฉลามอัตโนมัติ"
AutoKillFishCrewMemberText = "สมาชิกลูกเรือฆ่าปลาอัตโนมัติ"
SetSpeedBoatText = "ตั้งเรือเร็ว"
SpeedBoatText = "เรือเร็ว"
NoClipRockText = "โนคลิป ร็อค"
SelectBringBoatText = "เลือกนำเรือ"
BringBoatText = "นำเรือ"
-- Rainbow Haki
RainbowHakiText = "ฮาคิสีรุ้ง"
AutoRainbowHakiText = "ออโต้เรนโบว์ฮาคิ"
AutoRainbowHakiHopText = "ออโต้ เรนโบว์ ฮากิ [ฮอป]"
-- Item
ItemText = "รายการ"
AutoEvoRaceV2Text = "ออโต้ อีโว เรซ V2"
AutoBartiloQuestText = "ออโต้ บาร์ติโล เควส"
AutoRengokuSwordsText = "ดาบเรนโกกุอัตโนมัติ"
AutoBuyLegendarySwordText = "ซื้อดาบในตำนานอัตโนมัติ"
AutoBuyEnchancementText = "เสริมประสิทธิภาพการซื้ออัตโนมัติ"
AutoMusketeerHatText = "หมวกทหารเสือออโต้"
AutoHolyTorchText = "คบเพลิงศักดิ์สิทธิ์อัตโนมัติ"
AutoYamaText = "ออโต้ ยามา"
-- Observation
ObservationText = "การสังเกต"
AutoFarmObservationHakiText = "ฮาคิสังเกตการณ์ฟาร์มอัตโนมัติ"
AutoFarmObservationHakiHopText = "ฮาคิสังเกตการณ์ฟาร์มอัตโนมัติ [ฮอป]"
-- Cursed Dual Katana
CursedDualKatanaText = "คาตานะคู่ต้องสาป"
AutoCursedDualKatanaText = "คาตานะคู่คำสาปอัตโนมัติ"
-- Yama Quest
YamaQuestText = "ยามาเควส"
AutoYamaQuestOneText = "ออโต้ยามาเควส [1]"
AutoYamaQuestTwoText = "ออโต้ยามาเควส [2]"
MobAuraText = "ม็อบออร่า"
-- Rip Indar
RipIndraText = "ริพ อินดาร์"
AutoRipIndraBossText = "ฟาร์มออโต้ริปอินดาร์ [Boss]"
-- Cake Prince
CakePrinceText = "เค้กเจ้าชาย"
AutoFarmCakePrinceText = "ออโต้ฟาร์มเค้กเจ้าชาย"
AutoSpawnCakePrinceText = "เจ้าชายเค้กวางไข่อัตโนมัติ"
-- Bone
BoneText = "กระดูก"
AutoFarmBoneText = "ออโต้ฟาร์มโบน"
AutoRandomBoneText = "กระดูกสุ่มอัตโนมัติ"
-- Elite Hunter
EliteHunterText = "อีลิทฮันเตอร์"
AutoEliteHunterText = "ออโต้ อีลิท ฮันเตอร์"
AutoEliteHunterHopText = "ออโต้ อีลีท ฮันเตอร์ [ฮอป]"
-- Stats
SelectStatsText = "เลือก สถิติ"
EnableStatsText = "เปิดใช้งานสถิติ"
EnableStatsKaitunText = "สถิติการเปิดใช้งาน Kaitun" 
--Shop
SelectShopText = "เลือกร้านค้า"
BuyOnSelectShopText = "ซื้อในร้านค้าที่เลือก"
-- Island
SelectIslandText = "เลือกเกาะ"
TeleportToFirstWorldText = "เทเลพอร์ตสู่โลกที่หนึ่ง"
TeleportToSecondWorldText = "เทเลพอร์ตไปยังโลกที่สอง"
TeleportToThirdWorldText = "เทเลพอร์ตไปยังโลกที่สาม"
TeleportToIslandText = "เทเลพอร์ตไปยังเกาะ"
StopTeleportText = "หยุดเทเลพอร์ต"
TeleportToAdvancedFruitDealerText = "เทเลพอร์ตไปยังผู้ค้าผลไม้ขั้นสูง"
TeleportToLegendarySwordDealerText = "เทเลพอร์ตไปยังพ่อค้าดาบในตำนาน"
TeleportToMasterofEnhancementText = "เทเลพอร์ตไปยังปรมาจารย์แห่งการเสริมประสิทธิภาพ"
-- Mirage Island
MirageIslandText = "เกาะมิราจ"
AutoTeleportToMirageIsland = "เทเลพอร์ตอัตโนมัติไปยังเกาะมิราจ"
TeleportToGearText = "เทเลพอร์ตไปยังเกียร์"
TeleportToGearBlueText = "เทเลพอร์ตไปยังเกียร์บลู"
-- Kitsune Island
KitsuneIslandText = "เกาะคิตสึเนะ"
AutoTeleportToKitsuneIslandText = "เทเลพอร์ตอัตโนมัติไปยังเกาะคิตสึเนะ"
AutoTeleportToKitsuneShrineText = "เทเลพอร์ตอัตโนมัติไปยังศาลเจ้าคิทสึเนะ"
AutoCollectAzureEmberText = "รวบรวม Azure Ember อัตโนมัติ"
-- Raid
SelectChipsText = "เลือกชิป"
AutoBuyChipsText = "ซื้อชิปอัตโนมัติ"
AutoStartRaidText = "เริ่มการโจมตีอัตโนมัติ"
KillAuraText = "ฆ่าออร่า"
AutoNextIslandText = "ออโต้เน็กซ์ไอส์แลนด์"
AutoAwakenedText = "ปลุกพลังอัตโนมัติ"
-- Law Raid Second World
LawRaidText = "การโจมตีทางกฎหมาย"
AutoBuyLawChipText = "ชิปกฎหมายซื้อรถยนต์"
AutoStartLawRaidText = "เริ่มการโจมตีกฎหมายอัตโนมัติ"
AutoKillLawText = "กฎหมายฆ่าอัตโนมัติ"
-- PvP
SelectPlayerText = "เลือก ผู้เล่น"
AimBotSkillText = "ทักษะเล็งบอท"
AimBotGunText = "ปืนเอมบอท"
TeleportToPlayerText = "เทเลพอร์ตไปยังผู้เล่น"
SpectatedPlayerText = "ผู้เล่นที่น่าจับตามอง"
AutoKillPlayerText = "ผู้เล่นฆ่าอัตโนมัติ"
EnablePvPText = "เปิดใช้งาน PvP"
SafeModeText = "โหมดปลอดภัย"
RespawnText = "เกิดใหม่"
-- Race V4

LockMoonText = "ล็อคมูน"
TeleportToTopGreatTreeText = "เทเลพอร์ตไปยังต้นไม้ใหญ่ยอด"
TeleportToTimpleOfTimeText = "เทเลพอร์ตไปยังช่วงเวลาแห่งกาลเวลา"
TeleportToLeverPullText = "เทเลพอร์ตไปยังคันโยกดึง"
TeleportToAcientOneText = "เทเลพอร์ตไปยัง Acient One"
UnlockLeverText = "ปลดล็อคคันโยก"
TeleportCyborgDoorText = "ประตูเทเลพอร์ตไซบอร์ก"
TeleportFishDoorText = "ประตูเทเลพอร์ตปลา"
TeleportGhoulDoorText = "ประตูเทเลพอร์ตปอบ"
TeleportHumanDoorText = "ประตูเทเลพอร์ตมนุษย์"
TeleportMinkDoorText = "ประตูเทเลพอร์ตมิงค์"
TeleportToSkyDoorText = "ประตูเทเลพอร์ตสกาย"
CompleteAngelTrialText = "เสร็จสิ้นการทดลองแองเจิล"
CompleteRabbitTrialText = "เสร็จสิ้นการทดลองใช้ Rabbit"
CompleteCyborgTrialText = "เสร็จสิ้นการทดลองใช้ Cyborg"
TeleportPVPZoneText = "เทเลพอร์ต PVP โซน"
TeleportToSafeZonePVPText = "เทเลพอร์ตไปยังเซฟโซน PVP"
-- Sniper Fruit
SelectFruitSniperText = "เลือกสไนเปอร์ผลไม้"
AutoBuyFruitSniperText = "ซื้อ Sniper ผลไม้อัตโนมัติ"
-- Fruit
FruitText = "ผลไม้"
SelectFruitText = "เลือกผลไม้"
AutoEatFruitText = "ออโต้กินผลไม้"
GetFruitInventoryText = "รับสินค้าคงคลังผลไม้"
AutoRandomFruitText = "ผลไม้สุ่มอัตโนมัติ"
AutoStoreFruitText = "ออโต้สโตร์ผลไม้"
AutoCollectFruitText = "เก็บผลไม้อัตโนมัติ"
-- ESP
ESPPlayerText = "ผู้เล่นอีเอสพี"
ESPChestText = "อกอีเอสพี"
ESPDevilFruitText = "ESP ผลไม้ปีศาจ"
ESPFlowerText = "อีพีเอส ฟลาวเวอร์"
ESPIslandText = "เกาะอีเอสพี"
ESPMirageText = "อีเอสพี มิราจ ไอส์แลนด์"
ESPKitsuneText = "อีเอสพี เกาะคิตสึเนะ"
--Miscellaneous Server
HopServerText = "ฮอปเซิร์ฟเวอร์"
HopLowPlayerServerText = "เซิร์ฟเวอร์ผู้เล่นกระโดดต่ำ"
RejoinServerText = "เข้าร่วมเซิร์ฟเวอร์อีกครั้ง"
--Miscellaneous Team
MiscellaneousTeamText = "ทีมงานเบ็ดเตล็ด"
JoinPiratesTeamText = "เข้าร่วมทีมโจรสลัด"
JoinMarinesTeamText = "เข้าร่วมทีมนาวิกโยธิน"
--Miscellaneous 
MiscellaneousText = "เบ็ดเตล็ด"
RedeemCodeAllText = "แลกรหัส [ทั้งหมด]"
DevilShopText = "ร้านปีศาจ"
ColorHakiText = "สีฮาคิ"
TitleNameText = "ชื่อเรื่อง"
AwakeningText = "การตื่นขึ้น"
RemoveFogText = "ลบหมอก"
ClockTimeDayText = "นาฬิกา เวลา วัน"
WalkOnWaterText = "เดินบนน้ำ"
infinityAbilityText = "ความสามารถอันไม่มีที่สิ้นสุด"
NoDashCooldownText = "ไม่มีคูลดาวน์แดช"
InfinitiesGeppoText = "อินฟินิตี้ เก็ปโป"
InfinitiesEnergyText = "พลังงานอินฟินิตี้"
-- Rain Fruit
RainFruitText = "ผลไม้สายฝน"
InstantLevelBeliEXPText = "ระดับทันที/เบลิ/EXP"
LevelText = "ระดับ"
EXPText = "ประสบการณ์"
BeliText = "เบลี"
FragmentsText = "เศษ"
HealthText = "สุขภาพ"
EnergyText = "พลังงาน"
-- Settings
BypassAntiCheatText = "บายพาส Anti-Cheat: Anti Flag"
AutoHakiText = "ออโต้ฮาคิ"
AutoKenText = "ออโต้ เคน"
BringMobText = "เอาม็อบมา."
RemoveDamageText = "ลบข้อความความเสียหาย"
RemoveNotifyText = "ลบการแจ้งเตือน"
WhiteScreenText = "หน้าจอสีขาว"
TweenSpeedText = "ความเร็วทวีน"
