-- Main
HomeText = "Trang chủ"
-- Config
ConfigText = "Cấu hình"
WeaponText = "vũ khí"
MethodText = "Phương pháp"
AttackTypeText = "Kiểu tấn công"
FastAttackText = "Tấn công nhanh"
-- Farming
FarmingText = "Nông nghiệp"
AutoFarmLevelText = "Cấp độ trang trại tự động"
AutoFarmNeareastMobsText = "Trang trại tự động"
ChestFarmGoodText = "Trang trại ngực [Tốt]"
ChestFarmTweenText = "Trang trại ngực [Tween]"
AutoCastleRaidText = "Đột kích lâu đài tự động"
-- Farming Mastery
FarmMasteryText = "Làm chủ nông nghiệp"
AutoFarmMasteryFruitText = "Làm chủ trái cây trong trang trại tự động"
AutoFarmMasteryGunText = "Tự động làm chủ súng trang trại"
KillAtText = "Giết Tại (%)"
-- Skill Mastery
SkillMasteryText = "Làm chủ kỹ năng"
SkillZText = "Kỹ năng Z"
SkillXText = "Kỹ năng X"
SkillCText = "Kỹ năng C"
SkillVText = "Kỹ năng V"
SkillFText = "Kỹ năng F"
-- Farming Boss
FarmBossText = "Ông chủ nông nghiệp"
SelectBossText = "Chọn ông chủ"
AutoFarmBossText = "Ông chủ trang trại ô tô"
AutoFarmBossQuestText = "Ông chủ trang trại ô tô [Nhiệm vụ]"
AutoFarmBossAllText = "Ông chủ trang trại ô tô [Tất cả]"
-- Material
MaterialText = "Vật liệu"
SelectMaterialText = "Chọn vật liệu"
AutoFarmMaterialAllText = "Vật liệu trang trại tự động"
-- World 1
StatusWorld1Text = "Tình trạng: Thế giới 1"
AutoNewWorldText = "Ô tô thế giới mới"
-- World 2
StatusWorld2Text = "Trạng thái: Thế giới 2"
AutoNewWorldThirdText = "Ô tô thế giới mới thứ ba"
-- Saber World 1
SaberFirstWorldText = "Saber | Từ đầu tiên"
AutoSaberText = "Kiếm tự động"
AutoPoleText = "Cực tự động"
-- Hallow Scythe World 3
HallowSyctheWorldText = "Lưỡi hái thần thánh"
AutoHallowScytheText = "Lưỡi hái tự động"
-- Factory World 2
FactorySecondWorldText = "Nhà máy | Thế giới thứ hai"
AutoFactoryText = "Nhà máy ô tô"
-- Ectoplasm
EctoplasmText = "Ngoại chất"
AutoFactoryText = "Tự động ngoại chất"
-- Sea Beast World 2
SeaBeastText = "Quái vật biển"
AutoSeaBeastKingText = "Vua quái vật biển tự động"
-- Dack Coat
DarkCoatText = "Áo khoác tối màu"
AutoDarkCoatText = "Áo khoác tối màu tự động"
-- Swan Glasses
SwanGlassesText = "Kính Thiên Nga"
AutoSwanGlassesText = "Kính thiên nga tự động"
AutoSwanGlassesHopText = "Kính thiên nga tự động [Hop]"
-- Sea Rough
SeaRoughText = "biển gồ ghề"
AutoKillEventText = "Tự động tiêu diệt [Sự kiện]"
AutoKillTerrorsharkText = "Tự động tiêu diệt cá mập khủng bố"
AutoKillPiranhaText = "Tự Động Giết Piranha"
AutoKillSharkText = "Tự động tiêu diệt cá mập"
AutoKillFishCrewMemberText = "Thành viên phi hành đoàn giết cá tự động"
SetSpeedBoatText = "Đặt tàu cao tốc"
SpeedBoatText = "Thuyền cao tốc"
NoClipRockText = "Đá Noclip"
-- Rainbow Haki
RainbowHakiText = "Haki cầu vồng"
AutoRainbowHakiText = "Haki cầu vồng tự động"
AutoRainbowHakiHopText = "Tự động cầu vồng Haki [Hop]"
-- Item
ItemText = "Mục"
AutoEvoRaceV2Text = "Cuộc đua tự động V2"
AutoBartiloQuestText = "Nhiệm vụ Bartilo tự động"
AutoRengokuSwordsText = "Kiếm Rengoku tự động"
AutoBuyLegendarySwordText = "Tự động mua thanh kiếm huyền thoại"
AutoBuyEnchancementText = "Nâng cao mua tự động"
AutoMusketeerHatText = "Mũ lính ngự lâm tự động"
AutoHolyTorchText = "Ngọn đuốc thánh tự động"
AutoYamaText = "Ôtô Yama"
-- Observation
ObservationText = "Quan sát"
AutoFarmObservationHakiText = "Haki quan sát trang trại ô tô"
AutoFarmObservationHakiHopText = "Haki quan sát trang trại tự động [Hop]"
-- Rip Indar
RipIndraText = "Rip Indar"
AutoRipIndraBossText = "Trang trại tự động Rip Indar [Ông chủ]"
-- Cake Prince
CakePrinceText = "Hoàng tử bánh ngọt"
AutoFarmCakePrinceText = "Hoàng tử bánh trang trại tự động"
AutoSpawnCakePrinceText = "Hoàng tử bánh sinh sản tự động"
-- Bone
BoneText = "Xương"
AutoFarmBone = "Xương trang trại tự động"
AutoRandomBone = "Xương ngẫu nhiên tự động"
-- Elite Hunter
EliteHunterText = "Thợ săn ưu tú"
AutoEliteHunterText = "Thợ săn ưu tú tự động"
AutoEliteHunterHopText = "Thợ săn ưu tú tự động [Hop]"
-- Stats
SelectStatsText = "Chọn số liệu thống kê"
EnableStatsText = "Bật thống kê"
EnableStatsKaitunText = "Thống kê Eanble Kaitun" 
--Shop
SelectShopText = "Chọn cửa hàng"
BuyOnSelectShopText = "Mua trên cửa hàng chọn lọc"
-- Island
SelectIslandText = "Chọn đảo"
TeleportToFirstWorldText = "Dịch chuyển đến thế giới thứ nhất"
TeleportToSecondWorldText = "Dịch chuyển đến thế giới thứ hai"
TeleportToThirdWorldText = "Dịch chuyển đến thế giới thứ ba"
TeleportToIslandText = "Dịch chuyển đến đảo"
StopTeleportText = "Dừng dịch chuyển tức thời"
TeleportToAdvancedFruitDealerText = "Dịch chuyển đến đại lý trái cây nâng cao"
TeleportToLegendarySwordDealerText = "Dịch chuyển đến người bán kiếm huyền thoại"
TeleportToMasterofEnhancementText = "Dịch chuyển tới bậc thầy cường hóa"
-- Mirage Island
MirageIslandText = "Đảo ảo ảnh"
AutoTeleportToMirageIsland = "Tự động dịch chuyển đến đảo Mirage"
TeleportToGearText = "Dịch chuyển tới bánh răng"
TeleportToGearBlueText = "Dịch chuyển tới Gear Blue"
-- Kitsune Island
KitsuneIslandText = "Đảo Kitsune"
AutoTeleportToKitsuneIslandText = "Tự động dịch chuyển đến đảo Kitsune"
AutoTeleportToKitsuneShrineText = "Tự động dịch chuyển đến đền Kitsune"
AutoCollectAzureEmberText = "Tự động thu thập Azure Ember"
-- Raid
SelectChipsText = "Chọn chip"
AutoBuyChipsText = "Tự động mua chip"
AutoStartRaidText = "Tự động bắt đầu đột kích"
KillAuraText = "Giết hào quang"
AutoNextIslandText = "Đảo tự động tiếp theo"
AutoAwakenedText = "Tự động đánh thức"
-- Law Raid Second World
LawRaidText = "Cuộc đột kích pháp luật"
AutoBuyLawChipText = "Chip luật mua tự động"
AutoStartLawRaidText = "Tự động bắt đầu cuộc đột kích luật"
AutoKillLawText = "Luật giết tự động"
-- PvP
SelectPlayerText = "Chọn máy nghe nhạc"
AimBotSkillText = "Kỹ năng Aimbot"
AimBotGunText = "Súng Aimbot"
TeleportToPlayerText = "Dịch chuyển đến người chơi"
SpectatedPlayerText = "Người chơi được theo dõi"
AutoKillPlayerText = "Tự động tiêu diệt người chơi"
EnablePvPText = "PvP đã bật"
SafeModeText = "Chế độ an toàn"
RespawnText = "hồi sinh"
-- Race V4

LockMoonText = "Khóa Mặt Trăng"
TeleportToTopGreatTreeText = "Dịch chuyển đến đỉnh cây lớn"
TeleportToTimpleOfTimeText = "Dịch chuyển đến thời gian của thời gian"
TeleportToLeverPullText = "Dịch chuyển để kéo đòn bẩy"
TeleportToAcientOneText = "Dịch chuyển đến Acient One"
UnlockLeverText = "Mở khóa đòn bẩy"
TeleportCyborgDoorText = "Dịch chuyển cửa Cyborg"
TeleportFishDoorText = "Cửa cá dịch chuyển"
TeleportGhoulDoorText = "Dịch chuyển cửa Ghoul"
TeleportHumanDoorText = "Dịch chuyển cửa người"
TeleportMinkDoorText = "Dịch chuyển cửa chồn"
TeleportToSkyDoorText = "Dịch chuyển cửa trời"
CompleteAngelTrialText = "Thử nghiệm thiên thần hoàn chỉnh"
CompleteRabbitTrialText = "Thử nghiệm thỏ hoàn chỉnh"
CompleteCyborgTrialText = "Hoàn thành thử nghiệm Cyborg"
TeleportPVPZoneText = "Dịch chuyển khu vực PVP"
TeleportToSafeZonePVPText = "Dịch chuyển đến vùng an toàn PVP"
-- Sniper Fruit
SelectFruitSniperText = "Chọn bắn tỉa trái cây"
AutoBuyFruitSniperText = "Tự động mua trái cây bắn tỉa"
-- Fruit
FruitText = "Hoa quả"
SelectFruitText = "Chọn trái cây"
AutoEatFruitText = "Tự động ăn trái cây"
GetFruitInventoryText = "Nhận kho trái cây"
AutoRandomFruitText = "Tự động trái cây ngẫu nhiên"
AutoStoreFruitText = "Cửa hàng trái cây tự động"
-- ESP
ESPPlayerText = "Người chơi ESP"
ESPChestText = "Rương ESP"
ESPDevilFruitText = "Trái ác quỷ ESP"
ESPFlowerText = "Hoa ESP"
ESPIslandText = "Đảo ESP"
--Miscellaneous Server
HopServerText = "Máy chủ hợp tác"
HopLowPlayerServerText = "Máy chủ có trình phát thấp Hop"
RejoinServerText = "Tham gia lại máy chủ"
--Miscellaneous Team
MiscellaneousTeamText = "Đội ngũ khác"
JoinPiratesTeamText = "Tham gia đội cướp biển"
JoinMarinesTeamText = "Tham gia đội Thủy quân lục chiến"
--Miscellaneous 
MiscellaneousText = "Điều khoản khác"
RedeemCodeAllText = "Đổi mã [Tất cả]"
DevilShopText = "Cửa hàng quỷ"
ColorHakiText = "Haki màu"
TitleNameText = "Tên tiêu đề"
AwakeningText = "Thức tỉnh"
RemoveFogText = "Loại bỏ sương mù"
ClockTimeDayText = "Đồng HồThời Gian Ngày"
WalkOnWaterText = "Đi trên nước"
infinityAbilityText = "khả năng vô cực"
NoDashCooldownText = "Không có thời gian hồi chiêu"
InfinitiesGeppoText = "Geppo vô cực"
InfinitiesEnergyText = "Năng lượng vô cực"
-- Rain Fruit
RainFruitText = "Quả Mưa"
InstantLevelBeliEXPText = "Cấp tức thì/Beli/EXP"
LevelText = "Mức độ"
EXPText = "EXP"
BeliText = "Beli"
FragmentsText = "Mảnh vỡ"
HealthText = "Sức khỏe"
EnergyText = "Năng lượng"
-- Settings
BypassAntiCheatText = "Bỏ qua chống gian lận: Chống cờ"
AutoHakiText = "Haki tự động"
AutoKenText = "Xe Ken"
BringMobText = "Mang theo đám đông"
RemoveDamageText = "Xóa văn bản thiệt hại"
RemoveNotifyText = "Xóa thông báo"
WhiteScreenText = "Màn hình trắng"

